---
- name: "генерация пароля для admin"
  set_fact:
    random_admin_pass: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=12') }}"

- name: "генерация пароля для user"
  set_fact:
    random_user_pass: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=12') }}"
