---
- name: "Установка Haproxy"
  yum:
    name: haproxy
    state: present
    update_cache: yes
  when:
    - ansible_distribution == "CentOS"

- name: "Установка Haproxy"
  apt:
    name: haproxy
    state: present
    update_cache: no
  when:
    - ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
